### ISSUE TITLE
Clipboard has no valid JSON content

### ISSUE THREAD

**Issue by ristomatti** [GregorBiswanger/VSCode-json2ts#6]
The extension doesn't seem to work anymore or at least for me. If I try to convert a valid JSON from clipboard I get `Clipboard has no valid JSON content` in dev console.

Also when trying to use the REST call with the REST endpoint I got the JSON from I get `No valid REST-Service URL`.

**Comment by GregorBiswanger** [comment]
Thanks for your feedback! 
Can you test your JSON with http://jsonlint.com please.

**Comment by ristomatti** [comment]
I can reproduce the issue with any JSON. For example:
```json
{
	"value": "test"
}
```

**Comment by Krossmaskinen** [comment]
I've got almost the same issue, but I don't even get the console output. Nothing happens.

**Comment by ghost** [comment]
don't work
`Clipboard has no valid JSON content ` 
{
	"value": "test"
}

**Comment by psimsa** [comment]
I have the same issue.
@GregorBiswanger Can you please post a sample JSON content that's supposed to work?
P.

**Comment by yarkovaleksei** [comment]
VSCode 1.23.1
Ubuntu 18.04

Valid JSON: `{"value":"test"}`

Extension not work.

Error message: **Clipboard has no valid JSON content**

**Comment by CODEheures** [comment]
Solution:
`sudo apt-get install xclip`

**Comment by Demetri0** [comment]
@GregorBiswanger I think you need to add this instruction to readme

**Comment by nvmt2** [comment]
// not work
`{
	"value": "test"
},`

// work ( don't copy commas )
`{
	"value": "test"
	}`
